---
# tasks file for ansible-openvswitch

- include: dist_vars.yml

- include: install.yml

- include: service.yml

- include: system_tuning.yml

- include: bridges.yml

- include: ports.yml

# vim: set ts=2 sw=2:
